export enum WidgetCopyPasteEnum {
    WIDGET_COPIED = 'WIDGET_COPIED',
    COPY_ERROR_FAILED_TO_COPY_WIDGET = 'COPY_ERROR_FAILED_TO_COPY_WIDGET',

    WIDGET_PASTED = 'WIDGET_PASTED',
    PASTE_WIDGET_MODAL_OPENED = 'PASTE_WIDGET_MODAL_OPENED',
    PASTE_ERROR_CANNOT_COPY_DEPENDENT_WIDGETS_ACROSS_DIFFERENT_REPORT = 'PASTE_ERROR_CANNOT_COPY_DEPENDENT_WIDGETS_ACROSS_DIFFERENT_REPORT',
    PASTE_ERROR_INVALID_CONTENTS_IN_CLIPBOARD = 'PASTE_ERROR_INVALID_CONTENTS_IN_CLIPBOARD'
}
