export enum AddPortSource {
    EXPLORE_ADD_PORT_SOURCE_UNSPECIFIED = 0,
    INTRO_SCREEN = 1,
    PORTFOLIO_HEADER_BAR = 2,
    ADD_PORT_MODAL = 3,
    BATCH_SCREEN_MODAL = 4,
    BENCHMARK_SELECTOR = 5,
    SECURITY_SEARCH = 6,
    ADVANCED_RISK_SETTINGS_MODAL = 7,
    INVESTMENT_UNIVERSE_FORM = 8
}
export enum ExplorePortfolioTypeEnum {
    EXPLORE_PORTFOLIO_TYPE_UNSPECIFIED = 0,
    PORTFOLIO = 1,
    INDEX_HISTORY = 2,
    WHAT_IF = 3,
    CREATE_FROM_SCRATCH = 4,
    THROUGH_TIME_ANALYSIS_SECTOR = 5,
    THROUGH_TIME_ANALYSIS_PORTFOLIO = 6,
    POINT_IN_TIME_ANALYSIS = 7
}

export enum ExplorePortfolioFavoriteTypeEnum {
    EXPLORE_FAVORITE_TYPE_UNSPECIFIED = 0,
    EXPLORE_FAVORITE_TYPE_SHARED = 1,
    EXPLORE_FAVORITE_TYPE_PERSONAL = 2
}
