/**
 * Enum for Factor Data Widget Analytic
 */
export enum FactorDataAnalytic {
    FACTOR_DATA_ANALYTIC_UNSPECIFIED = 0,
    FACTOR_DATA_ANALYTIC_FACTOR_LEVELS = 1,
    FACTOR_DATA_ANALYTIC_FACTOR_RETURNS = 2,
    FACTOR_DATA_ANALYTIC_CUMULATIVE_RETURNS = 3,
    FACTOR_DATA_ANALYTIC_VOLATILITIES = 4,
    FACTOR_DATA_ANALYTIC_CORRELATIONS = 5,
    FACTOR_DATA_ANALYTIC_REGRESSION_BETAS = 6,
}
