/**
 * Enum for Rule Units
 */
export enum RuleUnit {
    NOTIONAL_MV = 'NOTIONAL_VALUE',
    NOTIONAL_MV_ACTIVE = 'NOTIONAL_VALUE',
    NAV_GROUP = 'NOTIONAL_VALUE',
    PCT_NOTIONAL_VAL = 'PERCENT_NAV',
    PCT_NOTIONAL_VAL_ACTIVE = 'PERCENT_NAV',
    CUR_FACE = 'TRADING_UNITS',
    MARKET_VALUE = 'MARKET_VALUE'
}
