import {AuxAdvancedFilterModel} from '@blk/aladdin-angular-components';
import {DataFormatter, OverrideDateColumnOption, ScenarioColumnOption} from '@blk/explore-ui-column-option';
import {RiskSettings} from '@blk/explore-ui-risk';
import {CellValueChangedEvent, EditableCallback, RowNode, ValueSetterFunc} from 'ag-grid-community';

/**
 * Represents the column definition which is part of the widget within the RequestAdapterConfig
 */

export interface VizualizationColumnConfig {
    originalColumnTitle: string;
    columnTag: string;
    columnKey: string;
    columnTitle: string;
    dataType: string;
    isHidden: boolean;
    isSubtotalable: boolean;
    formatter: {
        format: Function,
        formatInShort?: Function,
        convertToRaw?: Function
    };
    splitColumnHeaderName?: string;
    width?: number;
    flex?: number;
    pinned?: boolean | string | 'left' | 'right';

    // riskSettings and scenarioSettings are needed for footnote
    riskSettings?: RiskSettings;
    scenarioSettings?: ScenarioColumnOption;
    overrideDateColumnOption?: OverrideDateColumnOption;
    scale?: string;
    editableCallback?: EditableCallback;
    onCellValueChanged?: (params: CellValueChangedEvent) => void;
    cellEditor?: any;
    valueSetter?: ValueSetterFunc<RowNode, string>;
}

/**
 * Represents the RequestParams that are generated by the widget with the limited view needed for the qbstr adapter (we should expand this IMO)
 */
export interface RequestAdapterConfig {
    columns: VizualizationColumnConfig[];
    splitColumns?: VizualizationColumnConfig[];
    columnFilters?: Record<string, AuxAdvancedFilterModel>;
    isCompareMode?: boolean;
    portfolio: string;
    widgetConfig?: string;
}

/**
 * Represents expost stats widget request config.. This has additional map of column key to column formatter which would be used to format each cell in table
 */
export interface ExpostStatsRequestAdapterConfig extends RequestAdapterConfig {
    columnFormatters: Map<string, DataFormatter>;
}

/**
 * Utility method to check if the object is an instance of this.
 */
export function isExpostStatsConfig(object: any): object is ExpostStatsRequestAdapterConfig {
    return 'columnFormatters' in object;
}

