/**
 * Enum used for generic event type/name
 */
export enum EventType {
    BULK_SAVING = 'BULK_SAVING',
    WIDGET_INPUT_DONE_EVENT = 'WIDGET_INPUT_DONE_EVENT',
    PORTFOLIO_INPUT_DONE_EVENT = 'PORTFOLIO_INPUT_DONE_EVENT',
    ACRM_CUSTOM_LEGEND_CHANGE= 'ACRM_CUSTOM_LEGEND_CHANGE',
    ACRM_DATA_SCOPE_CHANGE  = 'ACRM_DATA_SCOPE_CHANGE',
    DEPRECATED_ACTIVE_SECTOR_CONSTRAINTS_RUN = 'DEPRECATED_ACTIVE_SECTOR_CONSTRAINTS_RUN'
}
