sonar.typescript.lcov.reportPaths=**/lcov.info
sonar.test.inclusions=src/**/*.spec.ts,projects/**/*.spec.ts
sonar.exclusions=**/*.spec.ts,\
@npm/**/*,\
npm/**/*,\
sonar-project/**/*,\
node_modules/**,\
**/*.json,\
**/*.js,\
src/main.ts,\
**/coverage/**/*,\
**/scripts/**/*,\
**/dist/**/*,\
**/e2e/**/*,\
**/setupJest.ts,\
**/node_modules/**,\
test_reports/**,\
**/test-reports/**/*,\
**/__sonar/**/*,\
**/.nyc_output/**/*,\
/jest.global-mocks.ts
sonar.coverage.exclusions=**/grafana-faro-initializer.ts
