/**
 * TelemetryActionConstants is used to specify the type of event we want to track for Portfolios, Columns or Favorites
 */

export class TelemetryActionConstants {
    static readonly GENERIC_EVENT = 'GENERIC_EVENT';
    static readonly PORTFOLIO = {
        ADD_PORTFOLIO: 'ADD PORTFOLIO'
    };
    static readonly COLUMN = {
        SHOW_COLUMN_DEFINITION: 'SHOW COLUMN DEFINITION',
        COLUMN_FILTER: 'COLUMN FILTER',
        STRESS_SCENARIO_CREATION: 'STRESS SCENARIO CREATION',
    };
    static readonly FAVORITE = {
        LOAD_FAVORITE: 'LOAD FAVORITE',
        LOAD_PORTFOLIO: 'LOAD_PORTFOLIO'
    };
    static readonly  MENU_OPTIONS = {
        RUN_ALL_REPORTS: 'RUN ALL REPORTS',
        GET_WORKSPACE_URL: 'GET WORKSPACE URL',
        SET_WORKSPACE_DATE: 'SET WORKSPACE DATE'
    };
    static readonly USER_BEHAVIOUR = {
        RELOAD_OR_CANCEL_REPORT : 'RELOAD OR CANCEL REPORT',
        WIDGET_SHOW_FOOTNOTES : 'WIDGET SHOW FOOTNOTES',
        RELOAD_WIDGET : 'RELOAD WIDGET',
        ADD_WIDGET: 'ADD WIDGET',
        WIDGET_COPY_PASTE: 'COPY_PASTE',
        COMPARISON_MODE: 'COMPARISON MODE',
        WIDGET_SEARCH: 'WIDGET SEARCH',
        COMPOSITION_CHANGE: 'COMPOSITION CHANGE',
        ADD_WHAT_IF_PORTFOLIO: 'ADD WHAT IF PORTFOLIO',
        CUSTOM_PORTFOLIO_STATS: 'CUSTOM PORTFOLIO STATS',
        EXPORT_TRADE_TABLE: 'EXPORT TRADE TABLE',
        CLICK_ON_OPTIMIZE_MODEL: 'CLICK ON OPTIMIZE MODEL',
        CLICK_ON_OPTIMIZATION_SUMMARY: 'CLICK ON OPTIMIZATION SUMMARY',
        CLICK_ON_RESET_COMPOSITION: 'CLICK ON RESET COMPOSITION',
        RUN_OPTIMIZATION: 'RUN OPTIMIZATION',
        RUN_OPTIMIZATION_CONSTRAINTS: 'RUN OPTIMIZATION CONSTRAINTS',
        RISK_BUDGETING_DETAILS: 'RISK BUDGETING DETAILS',
        LOAD_OPTIMIZATION_SCENARIOS: 'LOAD OPTIMIZATION SCENARIOS',
        CLICK_ON_ADD_CASH: 'CLICK ON ADD CASH',
        MODELLING_CLICK_ON_HELP: 'MODELLING CLICK ON HELP',
        UPLOAD_SECURITY_LIST_MODELLING: 'UPLOAD SECURITY LIST MODELLING',
        ADD_ENTITIES: 'ADD ENTITIES TO PORTFOLIO',
        CLICK_ON_GENERATE_API_REQUEST: 'CLICK ON GENERATE API REQUEST',
        CLICK_ON_EXCEL_EXPORT: 'CLICK ON EXCEL EXPORT',
        CLICK_ON_PDF_EXPORT: 'CLICK ON PDF EXPORT',
        CLICK_ON_DELETE_FAVORITE: 'CLICK ON DELETE FAVORITE',
        CLICK_ON_UI_ELEMENT: 'CLICK ON UI ELEMENT',
        SAVE_WHAT_IF: 'SAVE WHAT IF PORTFOLIO',
        INVESTMENT_UNIVERSE: 'INVESTMENT UNIVERSE',
        INVESTMENT_UNIVERSE_TYPE: 'INVESTMENT UNIVERSE TYPE',
        COLUMN_SEARCH_QUERY: 'COLUMN SEARCH QUERY',
        SEMANTIC_SEARCH_QUERY: 'SEMANTIC SEARCH QUERY',
        STYLE_ANALYSIS_COLUMNS: 'ADD STYLE ANALYSIS COLUMNS',
        FACTOR_DATA_WIDGET_TIME_SERIES_REQUEST: 'FACTOR DATA WIDGET TIME SERIES REQUEST',
        FACTOR_DATA_WIDGET_RISK_MATRIX_REQUEST: 'FACTOR DATA WIDGET RISK MATRIX REQUEST',
        PGS_CHART_LAUNCHED: 'PGS CHART LAUNCHED',
    };
    static readonly CUSTOM_CALC = {
        FORMULA_SHORTCUT_CLICKED : 'FORMULA SHORTCUT CLICKED'
    };
    static readonly UI_ERRORS  = {
        COLLAPSED_LOOK_THROUGH_ERROR: 'COLLAPSED LOOK THROUGH ERROR'
    };
    static readonly ADD_REQUEST_ID_TO_TELEMETRY_PAYLOAD = 'ADD_REQUEST_ID_TO_TELEMETRY_PAYLOAD';
    static readonly MAX_FAVORITE_ID = 2147483648;
}

